# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user/user-microservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/user/user-microservice.proto',
  package='user',
  syntax='proto3',
  serialized_options=_b('Z&github.com/wrs-news/node-protocol/user'),
  serialized_pb=_b('\n\"proto/user/user-microservice.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\"<\n\nNewUserReq\x12\r\n\x05login\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"I\n\rUpdateUserReq\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\x05\"\x17\n\tUserReqID\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1b\n\x0bUserReqUuid\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x1d\n\x0cUserReqLogin\x12\r\n\x05login\x18\x01 \x01(\t\"-\n\x0cSelectionReq\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"t\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\r\n\x05login\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0c\n\x04role\x18\x05 \x01(\x05\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\"f\n\tSelection\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x18\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\n.user.User\x12\r\n\x05total\x18\x04 \x01(\x05\x12\x11\n\tlast_page\x18\x05 \x01(\x05\x32\x94\x03\n\x0bUserService\x12*\n\nCreateUser\x12\x10.user.NewUserReq\x1a\n.user.User\x12*\n\x0bGetUserById\x12\x0f.user.UserReqID\x1a\n.user.User\x12.\n\rGetUserByUuid\x12\x11.user.UserReqUuid\x1a\n.user.User\x12\x30\n\x0eGetUserByLogin\x12\x12.user.UserReqLogin\x1a\n.user.User\x12+\n\nDeleteUser\x12\x11.user.UserReqUuid\x1a\n.user.User\x12-\n\nUpdateUser\x12\x13.user.UpdateUserReq\x1a\n.user.User\x12-\n\x06GetAll\x12\x12.user.SelectionReq\x1a\x0f.user.Selection\x12@\n\x0eHeartbeatCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB(Z&github.com/wrs-news/node-protocol/userb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_NEWUSERREQ = _descriptor.Descriptor(
  name='NewUserReq',
  full_name='user.NewUserReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='user.NewUserReq.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='user.NewUserReq.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='user.NewUserReq.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=133,
)


_UPDATEUSERREQ = _descriptor.Descriptor(
  name='UpdateUserReq',
  full_name='user.UpdateUserReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='user.UpdateUserReq.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='login', full_name='user.UpdateUserReq.login', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='user.UpdateUserReq.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='user.UpdateUserReq.role', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=208,
)


_USERREQID = _descriptor.Descriptor(
  name='UserReqID',
  full_name='user.UserReqID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='user.UserReqID.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=233,
)


_USERREQUUID = _descriptor.Descriptor(
  name='UserReqUuid',
  full_name='user.UserReqUuid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='user.UserReqUuid.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=262,
)


_USERREQLOGIN = _descriptor.Descriptor(
  name='UserReqLogin',
  full_name='user.UserReqLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='user.UserReqLogin.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=293,
)


_SELECTIONREQ = _descriptor.Descriptor(
  name='SelectionReq',
  full_name='user.SelectionReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='user.SelectionReq.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='user.SelectionReq.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=340,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='user.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='user.User.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='user.User.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='login', full_name='user.User.login', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='user.User.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='user.User.role', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='user.User.created_at', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='user.User.updated_at', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=458,
)


_SELECTION = _descriptor.Descriptor(
  name='Selection',
  full_name='user.Selection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='user.Selection.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='user.Selection.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='user.Selection.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='user.Selection.total', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_page', full_name='user.Selection.last_page', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=562,
)

_SELECTION.fields_by_name['data'].message_type = _USER
DESCRIPTOR.message_types_by_name['NewUserReq'] = _NEWUSERREQ
DESCRIPTOR.message_types_by_name['UpdateUserReq'] = _UPDATEUSERREQ
DESCRIPTOR.message_types_by_name['UserReqID'] = _USERREQID
DESCRIPTOR.message_types_by_name['UserReqUuid'] = _USERREQUUID
DESCRIPTOR.message_types_by_name['UserReqLogin'] = _USERREQLOGIN
DESCRIPTOR.message_types_by_name['SelectionReq'] = _SELECTIONREQ
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Selection'] = _SELECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewUserReq = _reflection.GeneratedProtocolMessageType('NewUserReq', (_message.Message,), dict(
  DESCRIPTOR = _NEWUSERREQ,
  __module__ = 'proto.user.user_microservice_pb2'
  # @@protoc_insertion_point(class_scope:user.NewUserReq)
  ))
_sym_db.RegisterMessage(NewUserReq)

UpdateUserReq = _reflection.GeneratedProtocolMessageType('UpdateUserReq', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEUSERREQ,
  __module__ = 'proto.user.user_microservice_pb2'
  # @@protoc_insertion_point(class_scope:user.UpdateUserReq)
  ))
_sym_db.RegisterMessage(UpdateUserReq)

UserReqID = _reflection.GeneratedProtocolMessageType('UserReqID', (_message.Message,), dict(
  DESCRIPTOR = _USERREQID,
  __module__ = 'proto.user.user_microservice_pb2'
  # @@protoc_insertion_point(class_scope:user.UserReqID)
  ))
_sym_db.RegisterMessage(UserReqID)

UserReqUuid = _reflection.GeneratedProtocolMessageType('UserReqUuid', (_message.Message,), dict(
  DESCRIPTOR = _USERREQUUID,
  __module__ = 'proto.user.user_microservice_pb2'
  # @@protoc_insertion_point(class_scope:user.UserReqUuid)
  ))
_sym_db.RegisterMessage(UserReqUuid)

UserReqLogin = _reflection.GeneratedProtocolMessageType('UserReqLogin', (_message.Message,), dict(
  DESCRIPTOR = _USERREQLOGIN,
  __module__ = 'proto.user.user_microservice_pb2'
  # @@protoc_insertion_point(class_scope:user.UserReqLogin)
  ))
_sym_db.RegisterMessage(UserReqLogin)

SelectionReq = _reflection.GeneratedProtocolMessageType('SelectionReq', (_message.Message,), dict(
  DESCRIPTOR = _SELECTIONREQ,
  __module__ = 'proto.user.user_microservice_pb2'
  # @@protoc_insertion_point(class_scope:user.SelectionReq)
  ))
_sym_db.RegisterMessage(SelectionReq)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'proto.user.user_microservice_pb2'
  # @@protoc_insertion_point(class_scope:user.User)
  ))
_sym_db.RegisterMessage(User)

Selection = _reflection.GeneratedProtocolMessageType('Selection', (_message.Message,), dict(
  DESCRIPTOR = _SELECTION,
  __module__ = 'proto.user.user_microservice_pb2'
  # @@protoc_insertion_point(class_scope:user.Selection)
  ))
_sym_db.RegisterMessage(Selection)


DESCRIPTOR._options = None

_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='user.UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=565,
  serialized_end=969,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateUser',
    full_name='user.UserService.CreateUser',
    index=0,
    containing_service=None,
    input_type=_NEWUSERREQ,
    output_type=_USER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserById',
    full_name='user.UserService.GetUserById',
    index=1,
    containing_service=None,
    input_type=_USERREQID,
    output_type=_USER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserByUuid',
    full_name='user.UserService.GetUserByUuid',
    index=2,
    containing_service=None,
    input_type=_USERREQUUID,
    output_type=_USER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserByLogin',
    full_name='user.UserService.GetUserByLogin',
    index=3,
    containing_service=None,
    input_type=_USERREQLOGIN,
    output_type=_USER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteUser',
    full_name='user.UserService.DeleteUser',
    index=4,
    containing_service=None,
    input_type=_USERREQUUID,
    output_type=_USER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateUser',
    full_name='user.UserService.UpdateUser',
    index=5,
    containing_service=None,
    input_type=_UPDATEUSERREQ,
    output_type=_USER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='user.UserService.GetAll',
    index=6,
    containing_service=None,
    input_type=_SELECTIONREQ,
    output_type=_SELECTION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HeartbeatCheck',
    full_name='user.UserService.HeartbeatCheck',
    index=7,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
