# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tass-parser.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tass-parser.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x0cHeaderParams\x12\x12\n\nuser_agent\x18\x01 \x01(\t\x12\x0e\n\x06\x63ookie\x18\x02 \x01(\t\"B\n\x0c\x46ilterParams\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\"B\n\x08TassData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04link\x18\x02 \x01(\t\x12\x0b\n\x03img\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\x03\x32\xc6\x01\n\x11TassParserService\x12@\n\x12UpdateHeaderParams\x12\x12.user.HeaderParams\x1a\x16.google.protobuf.Empty\x12-\n\x07GetData\x12\x12.user.FilterParams\x1a\x0e.user.TassData\x12@\n\x0eHeartbeatCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB/Z-github.com/wrs-news/node-protocol/parser/tassb\x06proto3')



_HEADERPARAMS = DESCRIPTOR.message_types_by_name['HeaderParams']
_FILTERPARAMS = DESCRIPTOR.message_types_by_name['FilterParams']
_TASSDATA = DESCRIPTOR.message_types_by_name['TassData']
HeaderParams = _reflection.GeneratedProtocolMessageType('HeaderParams', (_message.Message,), {
  'DESCRIPTOR' : _HEADERPARAMS,
  '__module__' : 'tass_parser_pb2'
  # @@protoc_insertion_point(class_scope:user.HeaderParams)
  })
_sym_db.RegisterMessage(HeaderParams)

FilterParams = _reflection.GeneratedProtocolMessageType('FilterParams', (_message.Message,), {
  'DESCRIPTOR' : _FILTERPARAMS,
  '__module__' : 'tass_parser_pb2'
  # @@protoc_insertion_point(class_scope:user.FilterParams)
  })
_sym_db.RegisterMessage(FilterParams)

TassData = _reflection.GeneratedProtocolMessageType('TassData', (_message.Message,), {
  'DESCRIPTOR' : _TASSDATA,
  '__module__' : 'tass_parser_pb2'
  # @@protoc_insertion_point(class_scope:user.TassData)
  })
_sym_db.RegisterMessage(TassData)

_TASSPARSERSERVICE = DESCRIPTOR.services_by_name['TassParserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-github.com/wrs-news/node-protocol/parser/tass'
  _HEADERPARAMS._serialized_start=56
  _HEADERPARAMS._serialized_end=106
  _FILTERPARAMS._serialized_start=108
  _FILTERPARAMS._serialized_end=174
  _TASSDATA._serialized_start=176
  _TASSDATA._serialized_end=242
  _TASSPARSERSERVICE._serialized_start=245
  _TASSPARSERSERVICE._serialized_end=443
# @@protoc_insertion_point(module_scope)
