# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65rror.proto\x12\x04\x63ore\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\"^\n\x05\x45rror\x12*\n\x04null\x18\x01 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x00\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x10.core.ErrorValueH\x00\x42\x06\n\x04kind\"f\n\nErrorValue\x12+\n\x0einternal_error\x18\x01 \x01(\x0b\x32\x13.core.InternalError\x12+\n\x0e\x65xternal_error\x18\x02 \x01(\x0b\x32\x13.core.ExternalError\"A\n\rInternalError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tbacktrace\x18\x03 \x01(\t\".\n\rExternalError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\tB(Z&github.com/wrs-news/node-protocol/coreb\x06proto3')



_ERROR = DESCRIPTOR.message_types_by_name['Error']
_ERRORVALUE = DESCRIPTOR.message_types_by_name['ErrorValue']
_INTERNALERROR = DESCRIPTOR.message_types_by_name['InternalError']
_EXTERNALERROR = DESCRIPTOR.message_types_by_name['ExternalError']
Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'error_pb2'
  # @@protoc_insertion_point(class_scope:core.Error)
  })
_sym_db.RegisterMessage(Error)

ErrorValue = _reflection.GeneratedProtocolMessageType('ErrorValue', (_message.Message,), {
  'DESCRIPTOR' : _ERRORVALUE,
  '__module__' : 'error_pb2'
  # @@protoc_insertion_point(class_scope:core.ErrorValue)
  })
_sym_db.RegisterMessage(ErrorValue)

InternalError = _reflection.GeneratedProtocolMessageType('InternalError', (_message.Message,), {
  'DESCRIPTOR' : _INTERNALERROR,
  '__module__' : 'error_pb2'
  # @@protoc_insertion_point(class_scope:core.InternalError)
  })
_sym_db.RegisterMessage(InternalError)

ExternalError = _reflection.GeneratedProtocolMessageType('ExternalError', (_message.Message,), {
  'DESCRIPTOR' : _EXTERNALERROR,
  '__module__' : 'error_pb2'
  # @@protoc_insertion_point(class_scope:core.ExternalError)
  })
_sym_db.RegisterMessage(ExternalError)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z&github.com/wrs-news/node-protocol/core'
  _ERROR._serialized_start=112
  _ERROR._serialized_end=206
  _ERRORVALUE._serialized_start=208
  _ERRORVALUE._serialized_end=310
  _INTERNALERROR._serialized_start=312
  _INTERNALERROR._serialized_end=377
  _EXTERNALERROR._serialized_start=379
  _EXTERNALERROR._serialized_end=425
# @@protoc_insertion_point(module_scope)
